// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sigalign
Rcpp::CharacterVector sigalign(Rcpp::CharacterVector adapters, std::vector<std::string> sequences, std::vector<std::string> ids, Rcpp::DataFrame misalignment_thresholds, int nthreads);
RcppExport SEXP _rad_sigalign(SEXP adaptersSEXP, SEXP sequencesSEXP, SEXP idsSEXP, SEXP misalignment_thresholdsSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type adapters(adaptersSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type sequences(sequencesSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type ids(idsSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type misalignment_thresholds(misalignment_thresholdsSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(sigalign(adapters, sequences, ids, misalignment_thresholds, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// sigalign_stats
Rcpp::DataFrame sigalign_stats(Rcpp::CharacterVector adapters, std::vector<std::string> sequences, int nthreads);
RcppExport SEXP _rad_sigalign_stats(SEXP adaptersSEXP, SEXP sequencesSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type adapters(adaptersSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type sequences(sequencesSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(sigalign_stats(adapters, sequences, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// sigrun
Rcpp::CharacterVector sigrun(const Rcpp::DataFrame& read_layout, const Rcpp::DataFrame& misalignment_threshold, const Rcpp::StringVector& sigstrings, bool verbose);
RcppExport SEXP _rad_sigrun(SEXP read_layoutSEXP, SEXP misalignment_thresholdSEXP, SEXP sigstringsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type read_layout(read_layoutSEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type misalignment_threshold(misalignment_thresholdSEXP);
    Rcpp::traits::input_parameter< const Rcpp::StringVector& >::type sigstrings(sigstringsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(sigrun(read_layout, misalignment_threshold, sigstrings, verbose));
    return rcpp_result_gen;
END_RCPP
}
// revcomp
Rcpp::StringVector revcomp(Rcpp::StringVector sequences);
RcppExport SEXP _rad_revcomp(SEXP sequencesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type sequences(sequencesSEXP);
    rcpp_result_gen = Rcpp::wrap(revcomp(sequences));
    return rcpp_result_gen;
END_RCPP
}
// sequence_to_bits
Rcpp::NumericVector sequence_to_bits(Rcpp::StringVector sequences);
RcppExport SEXP _rad_sequence_to_bits(SEXP sequencesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type sequences(sequencesSEXP);
    rcpp_result_gen = Rcpp::wrap(sequence_to_bits(sequences));
    return rcpp_result_gen;
END_RCPP
}
// sequence_to_bitlist
List sequence_to_bitlist(Rcpp::StringVector sequences);
RcppExport SEXP _rad_sequence_to_bitlist(SEXP sequencesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type sequences(sequencesSEXP);
    rcpp_result_gen = Rcpp::wrap(sequence_to_bitlist(sequences));
    return rcpp_result_gen;
END_RCPP
}
// qual_to_bits
Rcpp::NumericVector qual_to_bits(Rcpp::StringVector sequences);
RcppExport SEXP _rad_qual_to_bits(SEXP sequencesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type sequences(sequencesSEXP);
    rcpp_result_gen = Rcpp::wrap(qual_to_bits(sequences));
    return rcpp_result_gen;
END_RCPP
}
// qual_to_bitlist
List qual_to_bitlist(StringVector sequences);
RcppExport SEXP _rad_qual_to_bitlist(SEXP sequencesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< StringVector >::type sequences(sequencesSEXP);
    rcpp_result_gen = Rcpp::wrap(qual_to_bitlist(sequences));
    return rcpp_result_gen;
END_RCPP
}
// bits_to_sequence
Rcpp::StringVector bits_to_sequence(Rcpp::NumericVector input, Rcpp::IntegerVector sequence_length);
RcppExport SEXP _rad_bits_to_sequence(SEXP inputSEXP, SEXP sequence_lengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type input(inputSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type sequence_length(sequence_lengthSEXP);
    rcpp_result_gen = Rcpp::wrap(bits_to_sequence(input, sequence_length));
    return rcpp_result_gen;
END_RCPP
}
// bits_to_hex
StringVector bits_to_hex(Rcpp::NumericVector input, int sequence_length);
RcppExport SEXP _rad_bits_to_hex(SEXP inputSEXP, SEXP sequence_lengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type input(inputSEXP);
    Rcpp::traits::input_parameter< int >::type sequence_length(sequence_lengthSEXP);
    rcpp_result_gen = Rcpp::wrap(bits_to_hex(input, sequence_length));
    return rcpp_result_gen;
END_RCPP
}
// revcomp_bits
Rcpp::NumericVector revcomp_bits(Rcpp::NumericVector input, Rcpp::IntegerVector sequence_length);
RcppExport SEXP _rad_revcomp_bits(SEXP inputSEXP, SEXP sequence_lengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type input(inputSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type sequence_length(sequence_lengthSEXP);
    rcpp_result_gen = Rcpp::wrap(revcomp_bits(input, sequence_length));
    return rcpp_result_gen;
END_RCPP
}
// hamming_bits
IntegerVector hamming_bits(NumericVector int64_a, NumericVector int64_b, IntegerVector sequence_length);
RcppExport SEXP _rad_hamming_bits(SEXP int64_aSEXP, SEXP int64_bSEXP, SEXP sequence_lengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type int64_a(int64_aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type int64_b(int64_bSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type sequence_length(sequence_lengthSEXP);
    rcpp_result_gen = Rcpp::wrap(hamming_bits(int64_a, int64_b, sequence_length));
    return rcpp_result_gen;
END_RCPP
}
// generate_bit_mutations
Rcpp::NumericVector generate_bit_mutations(Rcpp::NumericVector sequences, IntegerVector sequence_length);
RcppExport SEXP _rad_generate_bit_mutations(SEXP sequencesSEXP, SEXP sequence_lengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sequences(sequencesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type sequence_length(sequence_lengthSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_bit_mutations(sequences, sequence_length));
    return rcpp_result_gen;
END_RCPP
}
// bit_substring
Rcpp::NumericVector bit_substring(Rcpp::NumericVector bit_sequences, int start_pos, int stop_pos);
RcppExport SEXP _rad_bit_substring(SEXP bit_sequencesSEXP, SEXP start_posSEXP, SEXP stop_posSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type bit_sequences(bit_sequencesSEXP);
    Rcpp::traits::input_parameter< int >::type start_pos(start_posSEXP);
    Rcpp::traits::input_parameter< int >::type stop_pos(stop_posSEXP);
    rcpp_result_gen = Rcpp::wrap(bit_substring(bit_sequences, start_pos, stop_pos));
    return rcpp_result_gen;
END_RCPP
}
// kmer_circ
Rcpp::NumericVector kmer_circ(SEXP sequence, int base_length, int kmerLength, bool verbose);
RcppExport SEXP _rad_kmer_circ(SEXP sequenceSEXP, SEXP base_lengthSEXP, SEXP kmerLengthSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sequence(sequenceSEXP);
    Rcpp::traits::input_parameter< int >::type base_length(base_lengthSEXP);
    Rcpp::traits::input_parameter< int >::type kmerLength(kmerLengthSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(kmer_circ(sequence, base_length, kmerLength, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rad_sigalign", (DL_FUNC) &_rad_sigalign, 5},
    {"_rad_sigalign_stats", (DL_FUNC) &_rad_sigalign_stats, 3},
    {"_rad_sigrun", (DL_FUNC) &_rad_sigrun, 4},
    {"_rad_revcomp", (DL_FUNC) &_rad_revcomp, 1},
    {"_rad_sequence_to_bits", (DL_FUNC) &_rad_sequence_to_bits, 1},
    {"_rad_sequence_to_bitlist", (DL_FUNC) &_rad_sequence_to_bitlist, 1},
    {"_rad_qual_to_bits", (DL_FUNC) &_rad_qual_to_bits, 1},
    {"_rad_qual_to_bitlist", (DL_FUNC) &_rad_qual_to_bitlist, 1},
    {"_rad_bits_to_sequence", (DL_FUNC) &_rad_bits_to_sequence, 2},
    {"_rad_bits_to_hex", (DL_FUNC) &_rad_bits_to_hex, 2},
    {"_rad_revcomp_bits", (DL_FUNC) &_rad_revcomp_bits, 2},
    {"_rad_hamming_bits", (DL_FUNC) &_rad_hamming_bits, 3},
    {"_rad_generate_bit_mutations", (DL_FUNC) &_rad_generate_bit_mutations, 2},
    {"_rad_bit_substring", (DL_FUNC) &_rad_bit_substring, 3},
    {"_rad_kmer_circ", (DL_FUNC) &_rad_kmer_circ, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_rad(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
