// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sigalign
Rcpp::CharacterVector sigalign(Rcpp::CharacterVector adapters, std::vector<std::string> sequences, std::vector<std::string> ids, const Rcpp::DataFrame& misalignment_threshold, int nthreads);
RcppExport SEXP _rad_sigalign(SEXP adaptersSEXP, SEXP sequencesSEXP, SEXP idsSEXP, SEXP misalignment_thresholdSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type adapters(adaptersSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type sequences(sequencesSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type ids(idsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type misalignment_threshold(misalignment_thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(sigalign(adapters, sequences, ids, misalignment_threshold, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// sigalign_stats
Rcpp::DataFrame sigalign_stats(Rcpp::CharacterVector adapters, std::vector<std::string> sequences, int nthreads);
RcppExport SEXP _rad_sigalign_stats(SEXP adaptersSEXP, SEXP sequencesSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type adapters(adaptersSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type sequences(sequencesSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(sigalign_stats(adapters, sequences, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// dl_dist_rcpp
Rcpp::IntegerVector dl_dist_rcpp(Rcpp::NumericVector src_input, Rcpp::NumericVector tgt_input, unsigned int maxDistance);
RcppExport SEXP _rad_dl_dist_rcpp(SEXP src_inputSEXP, SEXP tgt_inputSEXP, SEXP maxDistanceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type src_input(src_inputSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type tgt_input(tgt_inputSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type maxDistance(maxDistanceSEXP);
    rcpp_result_gen = Rcpp::wrap(dl_dist_rcpp(src_input, tgt_input, maxDistance));
    return rcpp_result_gen;
END_RCPP
}
// populate_whitelist
void populate_whitelist(NumericVector barcodes, NumericVector poisson_data, NumericVector counts, bool verbose);
RcppExport SEXP _rad_populate_whitelist(SEXP barcodesSEXP, SEXP poisson_dataSEXP, SEXP countsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type barcodes(barcodesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type poisson_data(poisson_dataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    populate_whitelist(barcodes, poisson_data, counts, verbose);
    return R_NilValue;
END_RCPP
}
// wl_to_df
Rcpp::DataFrame wl_to_df();
RcppExport SEXP _rad_wl_to_df() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(wl_to_df());
    return rcpp_result_gen;
END_RCPP
}
// clear_whitelist
void clear_whitelist();
RcppExport SEXP _rad_clear_whitelist() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    clear_whitelist();
    return R_NilValue;
END_RCPP
}
// whitelist_size
int whitelist_size();
RcppExport SEXP _rad_whitelist_size() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(whitelist_size());
    return rcpp_result_gen;
END_RCPP
}
// correct_barcodes_v1
NumericVector correct_barcodes_v1(NumericVector barcodes, bool verbose, int nthreads, int depth, int breadth);
RcppExport SEXP _rad_correct_barcodes_v1(SEXP barcodesSEXP, SEXP verboseSEXP, SEXP nthreadsSEXP, SEXP depthSEXP, SEXP breadthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type barcodes(barcodesSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< int >::type depth(depthSEXP);
    Rcpp::traits::input_parameter< int >::type breadth(breadthSEXP);
    rcpp_result_gen = Rcpp::wrap(correct_barcodes_v1(barcodes, verbose, nthreads, depth, breadth));
    return rcpp_result_gen;
END_RCPP
}
// correct_barcodes_v2
Rcpp::NumericVector correct_barcodes_v2(Rcpp::NumericVector barcodes, bool verbose, int nthreads, int maxDistance);
RcppExport SEXP _rad_correct_barcodes_v2(SEXP barcodesSEXP, SEXP verboseSEXP, SEXP nthreadsSEXP, SEXP maxDistanceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type barcodes(barcodesSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< int >::type maxDistance(maxDistanceSEXP);
    rcpp_result_gen = Rcpp::wrap(correct_barcodes_v2(barcodes, verbose, nthreads, maxDistance));
    return rcpp_result_gen;
END_RCPP
}
// correct_barcodes_v3
Rcpp::NumericVector correct_barcodes_v3(Rcpp::NumericVector barcodes, bool verbose, int nthreads, int breadth, int depth, int maxDistance);
RcppExport SEXP _rad_correct_barcodes_v3(SEXP barcodesSEXP, SEXP verboseSEXP, SEXP nthreadsSEXP, SEXP breadthSEXP, SEXP depthSEXP, SEXP maxDistanceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type barcodes(barcodesSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< int >::type breadth(breadthSEXP);
    Rcpp::traits::input_parameter< int >::type depth(depthSEXP);
    Rcpp::traits::input_parameter< int >::type maxDistance(maxDistanceSEXP);
    rcpp_result_gen = Rcpp::wrap(correct_barcodes_v3(barcodes, verbose, nthreads, breadth, depth, maxDistance));
    return rcpp_result_gen;
END_RCPP
}
// correct_barcodes_v4
Rcpp::NumericVector correct_barcodes_v4(Rcpp::NumericVector barcodes, bool verbose, int nthreads, int depth, int breadth, bool high_speed, int maxDistance);
RcppExport SEXP _rad_correct_barcodes_v4(SEXP barcodesSEXP, SEXP verboseSEXP, SEXP nthreadsSEXP, SEXP depthSEXP, SEXP breadthSEXP, SEXP high_speedSEXP, SEXP maxDistanceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type barcodes(barcodesSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< int >::type depth(depthSEXP);
    Rcpp::traits::input_parameter< int >::type breadth(breadthSEXP);
    Rcpp::traits::input_parameter< bool >::type high_speed(high_speedSEXP);
    Rcpp::traits::input_parameter< int >::type maxDistance(maxDistanceSEXP);
    rcpp_result_gen = Rcpp::wrap(correct_barcodes_v4(barcodes, verbose, nthreads, depth, breadth, high_speed, maxDistance));
    return rcpp_result_gen;
END_RCPP
}
// correct_barcodes_v5
Rcpp::NumericVector correct_barcodes_v5(Rcpp::NumericVector barcodes, bool verbose, int nthreads, int depth, int breadth, bool high_speed, int maxDistance);
RcppExport SEXP _rad_correct_barcodes_v5(SEXP barcodesSEXP, SEXP verboseSEXP, SEXP nthreadsSEXP, SEXP depthSEXP, SEXP breadthSEXP, SEXP high_speedSEXP, SEXP maxDistanceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type barcodes(barcodesSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< int >::type depth(depthSEXP);
    Rcpp::traits::input_parameter< int >::type breadth(breadthSEXP);
    Rcpp::traits::input_parameter< bool >::type high_speed(high_speedSEXP);
    Rcpp::traits::input_parameter< int >::type maxDistance(maxDistanceSEXP);
    rcpp_result_gen = Rcpp::wrap(correct_barcodes_v5(barcodes, verbose, nthreads, depth, breadth, high_speed, maxDistance));
    return rcpp_result_gen;
END_RCPP
}
// correct_barcodes_v6
Rcpp::NumericVector correct_barcodes_v6(Rcpp::NumericVector barcodes, bool verbose, int nthreads, int maxDistance);
RcppExport SEXP _rad_correct_barcodes_v6(SEXP barcodesSEXP, SEXP verboseSEXP, SEXP nthreadsSEXP, SEXP maxDistanceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type barcodes(barcodesSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< int >::type maxDistance(maxDistanceSEXP);
    rcpp_result_gen = Rcpp::wrap(correct_barcodes_v6(barcodes, verbose, nthreads, maxDistance));
    return rcpp_result_gen;
END_RCPP
}
// correct_barcodes_v7
Rcpp::NumericVector correct_barcodes_v7(Rcpp::NumericVector barcodes, bool verbose, int nthreads, int depth, int breadth, bool high_speed, int maxDistance);
RcppExport SEXP _rad_correct_barcodes_v7(SEXP barcodesSEXP, SEXP verboseSEXP, SEXP nthreadsSEXP, SEXP depthSEXP, SEXP breadthSEXP, SEXP high_speedSEXP, SEXP maxDistanceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type barcodes(barcodesSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< int >::type depth(depthSEXP);
    Rcpp::traits::input_parameter< int >::type breadth(breadthSEXP);
    Rcpp::traits::input_parameter< bool >::type high_speed(high_speedSEXP);
    Rcpp::traits::input_parameter< int >::type maxDistance(maxDistanceSEXP);
    rcpp_result_gen = Rcpp::wrap(correct_barcodes_v7(barcodes, verbose, nthreads, depth, breadth, high_speed, maxDistance));
    return rcpp_result_gen;
END_RCPP
}
// correct_barcodes
Rcpp::NumericVector correct_barcodes(Rcpp::NumericVector barcodes, bool verbose, int nthreads, int depth, int breadth, bool high_speed, int maxDistance);
RcppExport SEXP _rad_correct_barcodes(SEXP barcodesSEXP, SEXP verboseSEXP, SEXP nthreadsSEXP, SEXP depthSEXP, SEXP breadthSEXP, SEXP high_speedSEXP, SEXP maxDistanceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type barcodes(barcodesSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< int >::type depth(depthSEXP);
    Rcpp::traits::input_parameter< int >::type breadth(breadthSEXP);
    Rcpp::traits::input_parameter< bool >::type high_speed(high_speedSEXP);
    Rcpp::traits::input_parameter< int >::type maxDistance(maxDistanceSEXP);
    rcpp_result_gen = Rcpp::wrap(correct_barcodes(barcodes, verbose, nthreads, depth, breadth, high_speed, maxDistance));
    return rcpp_result_gen;
END_RCPP
}
// sig_extractor
Rcpp::List sig_extractor(const DataFrame& read_layout, const DataFrame& misalignment_threshold, const DataFrame& df, const CharacterVector& processed_sigstrings, bool verbose);
RcppExport SEXP _rad_sig_extractor(SEXP read_layoutSEXP, SEXP misalignment_thresholdSEXP, SEXP dfSEXP, SEXP processed_sigstringsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type read_layout(read_layoutSEXP);
    Rcpp::traits::input_parameter< const DataFrame& >::type misalignment_threshold(misalignment_thresholdSEXP);
    Rcpp::traits::input_parameter< const DataFrame& >::type df(dfSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type processed_sigstrings(processed_sigstringsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(sig_extractor(read_layout, misalignment_threshold, df, processed_sigstrings, verbose));
    return rcpp_result_gen;
END_RCPP
}
// sig_extractor_v2
Rcpp::DataFrame sig_extractor_v2(const DataFrame& read_layout, const DataFrame& misalignment_threshold, DataFrame& df, const CharacterVector& processed_sigstrings, bool verbose);
RcppExport SEXP _rad_sig_extractor_v2(SEXP read_layoutSEXP, SEXP misalignment_thresholdSEXP, SEXP dfSEXP, SEXP processed_sigstringsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type read_layout(read_layoutSEXP);
    Rcpp::traits::input_parameter< const DataFrame& >::type misalignment_threshold(misalignment_thresholdSEXP);
    Rcpp::traits::input_parameter< DataFrame& >::type df(dfSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type processed_sigstrings(processed_sigstringsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(sig_extractor_v2(read_layout, misalignment_threshold, df, processed_sigstrings, verbose));
    return rcpp_result_gen;
END_RCPP
}
// sigrun
Rcpp::CharacterVector sigrun(const Rcpp::DataFrame& read_layout, const Rcpp::DataFrame& misalignment_threshold, const Rcpp::StringVector& sigstrings, int nthreads, bool verbose);
RcppExport SEXP _rad_sigrun(SEXP read_layoutSEXP, SEXP misalignment_thresholdSEXP, SEXP sigstringsSEXP, SEXP nthreadsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type read_layout(read_layoutSEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type misalignment_threshold(misalignment_thresholdSEXP);
    Rcpp::traits::input_parameter< const Rcpp::StringVector& >::type sigstrings(sigstringsSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(sigrun(read_layout, misalignment_threshold, sigstrings, nthreads, verbose));
    return rcpp_result_gen;
END_RCPP
}
// revcomp
Rcpp::StringVector revcomp(Rcpp::StringVector sequences);
RcppExport SEXP _rad_revcomp(SEXP sequencesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type sequences(sequencesSEXP);
    rcpp_result_gen = Rcpp::wrap(revcomp(sequences));
    return rcpp_result_gen;
END_RCPP
}
// sequence_to_bits
Rcpp::NumericVector sequence_to_bits(Rcpp::StringVector sequences);
RcppExport SEXP _rad_sequence_to_bits(SEXP sequencesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type sequences(sequencesSEXP);
    rcpp_result_gen = Rcpp::wrap(sequence_to_bits(sequences));
    return rcpp_result_gen;
END_RCPP
}
// sequence_to_bitlist
List sequence_to_bitlist(Rcpp::StringVector sequences);
RcppExport SEXP _rad_sequence_to_bitlist(SEXP sequencesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type sequences(sequencesSEXP);
    rcpp_result_gen = Rcpp::wrap(sequence_to_bitlist(sequences));
    return rcpp_result_gen;
END_RCPP
}
// qual_to_bits
Rcpp::NumericVector qual_to_bits(Rcpp::StringVector sequences);
RcppExport SEXP _rad_qual_to_bits(SEXP sequencesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type sequences(sequencesSEXP);
    rcpp_result_gen = Rcpp::wrap(qual_to_bits(sequences));
    return rcpp_result_gen;
END_RCPP
}
// qual_to_bitlist
List qual_to_bitlist(StringVector sequences);
RcppExport SEXP _rad_qual_to_bitlist(SEXP sequencesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< StringVector >::type sequences(sequencesSEXP);
    rcpp_result_gen = Rcpp::wrap(qual_to_bitlist(sequences));
    return rcpp_result_gen;
END_RCPP
}
// bits_to_sequence
Rcpp::StringVector bits_to_sequence(Rcpp::NumericVector input, Rcpp::IntegerVector sequence_length);
RcppExport SEXP _rad_bits_to_sequence(SEXP inputSEXP, SEXP sequence_lengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type input(inputSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type sequence_length(sequence_lengthSEXP);
    rcpp_result_gen = Rcpp::wrap(bits_to_sequence(input, sequence_length));
    return rcpp_result_gen;
END_RCPP
}
// bits_to_hex
StringVector bits_to_hex(Rcpp::NumericVector input, int sequence_length);
RcppExport SEXP _rad_bits_to_hex(SEXP inputSEXP, SEXP sequence_lengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type input(inputSEXP);
    Rcpp::traits::input_parameter< int >::type sequence_length(sequence_lengthSEXP);
    rcpp_result_gen = Rcpp::wrap(bits_to_hex(input, sequence_length));
    return rcpp_result_gen;
END_RCPP
}
// revcomp_bits
Rcpp::NumericVector revcomp_bits(Rcpp::NumericVector input, Rcpp::IntegerVector sequence_length);
RcppExport SEXP _rad_revcomp_bits(SEXP inputSEXP, SEXP sequence_lengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type input(inputSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type sequence_length(sequence_lengthSEXP);
    rcpp_result_gen = Rcpp::wrap(revcomp_bits(input, sequence_length));
    return rcpp_result_gen;
END_RCPP
}
// hamming_bits
IntegerVector hamming_bits(NumericVector int64_a, NumericVector int64_b, IntegerVector sequence_length);
RcppExport SEXP _rad_hamming_bits(SEXP int64_aSEXP, SEXP int64_bSEXP, SEXP sequence_lengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type int64_a(int64_aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type int64_b(int64_bSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type sequence_length(sequence_lengthSEXP);
    rcpp_result_gen = Rcpp::wrap(hamming_bits(int64_a, int64_b, sequence_length));
    return rcpp_result_gen;
END_RCPP
}
// generate_bit_mutations
Rcpp::NumericVector generate_bit_mutations(Rcpp::NumericVector sequences, IntegerVector sequence_length);
RcppExport SEXP _rad_generate_bit_mutations(SEXP sequencesSEXP, SEXP sequence_lengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sequences(sequencesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type sequence_length(sequence_lengthSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_bit_mutations(sequences, sequence_length));
    return rcpp_result_gen;
END_RCPP
}
// generate_recursive_mutations
Rcpp::NumericVector generate_recursive_mutations(Rcpp::NumericVector sequences, int mutation_rounds);
RcppExport SEXP _rad_generate_recursive_mutations(SEXP sequencesSEXP, SEXP mutation_roundsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sequences(sequencesSEXP);
    Rcpp::traits::input_parameter< int >::type mutation_rounds(mutation_roundsSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_recursive_mutations(sequences, mutation_rounds));
    return rcpp_result_gen;
END_RCPP
}
// bit_substring
Rcpp::NumericVector bit_substring(Rcpp::NumericVector bit_sequences, int start_pos, int stop_pos);
RcppExport SEXP _rad_bit_substring(SEXP bit_sequencesSEXP, SEXP start_posSEXP, SEXP stop_posSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type bit_sequences(bit_sequencesSEXP);
    Rcpp::traits::input_parameter< int >::type start_pos(start_posSEXP);
    Rcpp::traits::input_parameter< int >::type stop_pos(stop_posSEXP);
    rcpp_result_gen = Rcpp::wrap(bit_substring(bit_sequences, start_pos, stop_pos));
    return rcpp_result_gen;
END_RCPP
}
// kmer_circ
Rcpp::NumericVector kmer_circ(SEXP sequence, int base_length, int kmerLength, bool verbose);
RcppExport SEXP _rad_kmer_circ(SEXP sequenceSEXP, SEXP base_lengthSEXP, SEXP kmerLengthSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sequence(sequenceSEXP);
    Rcpp::traits::input_parameter< int >::type base_length(base_lengthSEXP);
    Rcpp::traits::input_parameter< int >::type kmerLength(kmerLengthSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(kmer_circ(sequence, base_length, kmerLength, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rad_sigalign", (DL_FUNC) &_rad_sigalign, 5},
    {"_rad_sigalign_stats", (DL_FUNC) &_rad_sigalign_stats, 3},
    {"_rad_dl_dist_rcpp", (DL_FUNC) &_rad_dl_dist_rcpp, 3},
    {"_rad_populate_whitelist", (DL_FUNC) &_rad_populate_whitelist, 4},
    {"_rad_wl_to_df", (DL_FUNC) &_rad_wl_to_df, 0},
    {"_rad_clear_whitelist", (DL_FUNC) &_rad_clear_whitelist, 0},
    {"_rad_whitelist_size", (DL_FUNC) &_rad_whitelist_size, 0},
    {"_rad_correct_barcodes_v1", (DL_FUNC) &_rad_correct_barcodes_v1, 5},
    {"_rad_correct_barcodes_v2", (DL_FUNC) &_rad_correct_barcodes_v2, 4},
    {"_rad_correct_barcodes_v3", (DL_FUNC) &_rad_correct_barcodes_v3, 6},
    {"_rad_correct_barcodes_v4", (DL_FUNC) &_rad_correct_barcodes_v4, 7},
    {"_rad_correct_barcodes_v5", (DL_FUNC) &_rad_correct_barcodes_v5, 7},
    {"_rad_correct_barcodes_v6", (DL_FUNC) &_rad_correct_barcodes_v6, 4},
    {"_rad_correct_barcodes_v7", (DL_FUNC) &_rad_correct_barcodes_v7, 7},
    {"_rad_correct_barcodes", (DL_FUNC) &_rad_correct_barcodes, 7},
    {"_rad_sig_extractor", (DL_FUNC) &_rad_sig_extractor, 5},
    {"_rad_sig_extractor_v2", (DL_FUNC) &_rad_sig_extractor_v2, 5},
    {"_rad_sigrun", (DL_FUNC) &_rad_sigrun, 5},
    {"_rad_revcomp", (DL_FUNC) &_rad_revcomp, 1},
    {"_rad_sequence_to_bits", (DL_FUNC) &_rad_sequence_to_bits, 1},
    {"_rad_sequence_to_bitlist", (DL_FUNC) &_rad_sequence_to_bitlist, 1},
    {"_rad_qual_to_bits", (DL_FUNC) &_rad_qual_to_bits, 1},
    {"_rad_qual_to_bitlist", (DL_FUNC) &_rad_qual_to_bitlist, 1},
    {"_rad_bits_to_sequence", (DL_FUNC) &_rad_bits_to_sequence, 2},
    {"_rad_bits_to_hex", (DL_FUNC) &_rad_bits_to_hex, 2},
    {"_rad_revcomp_bits", (DL_FUNC) &_rad_revcomp_bits, 2},
    {"_rad_hamming_bits", (DL_FUNC) &_rad_hamming_bits, 3},
    {"_rad_generate_bit_mutations", (DL_FUNC) &_rad_generate_bit_mutations, 2},
    {"_rad_generate_recursive_mutations", (DL_FUNC) &_rad_generate_recursive_mutations, 2},
    {"_rad_bit_substring", (DL_FUNC) &_rad_bit_substring, 3},
    {"_rad_kmer_circ", (DL_FUNC) &_rad_kmer_circ, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_rad(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
