# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sigalign <- function(adapters, sequences, misalignment_thresholds, nthreads) {
    .Call(`_rad_sigalign`, adapters, sequences, misalignment_thresholds, nthreads)
}

sigalign_stats <- function(adapters, sequences, nthreads = 1L) {
    .Call(`_rad_sigalign_stats`, adapters, sequences, nthreads)
}

test_read_layout_container_v2 <- function(read_layout, misalignment_threshold, verbose = TRUE) {
    invisible(.Call(`_rad_test_read_layout_container_v2`, read_layout, misalignment_threshold, verbose))
}

VarTest <- function(read_layout, verbose = TRUE) {
    invisible(.Call(`_rad_VarTest`, read_layout, verbose))
}

SigTest <- function(read_layout, misalignment_threshold, sigstrings, verbose = FALSE) {
    invisible(.Call(`_rad_SigTest`, read_layout, misalignment_threshold, sigstrings, verbose))
}

revcomp <- function(sequences) {
    .Call(`_rad_revcomp`, sequences)
}

sequence_to_bits <- function(sequences) {
    .Call(`_rad_sequence_to_bits`, sequences)
}

bits_to_sequence <- function(input, sequence_length) {
    .Call(`_rad_bits_to_sequence`, input, sequence_length)
}

