# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sigalign <- function(adapters, sequences, ids, misalignment_threshold, nthreads) {
    .Call(`_rad_sigalign`, adapters, sequences, ids, misalignment_threshold, nthreads)
}

sigalign_stats <- function(adapters, sequences, nthreads = 1L) {
    .Call(`_rad_sigalign_stats`, adapters, sequences, nthreads)
}

prep_read_layout_rcpp <- function(read_layout, misalignment_threshold, verbose) {
    invisible(.Call(`_rad_prep_read_layout_rcpp`, read_layout, misalignment_threshold, verbose))
}

generate_position_setup_test <- function(read_layout, misalignment_threshold) {
    invisible(.Call(`_rad_generate_position_setup_test`, read_layout, misalignment_threshold))
}

sig_extraction <- function(read_layout, misalignment_threshold, df, processed_sigstrings, verbose) {
    .Call(`_rad_sig_extraction`, read_layout, misalignment_threshold, df, processed_sigstrings, verbose)
}

sigrun <- function(read_layout, misalignment_threshold, sigstrings, nthreads = 1L, verbose = FALSE) {
    .Call(`_rad_sigrun`, read_layout, misalignment_threshold, sigstrings, nthreads, verbose)
}

revcomp <- function(sequences) {
    .Call(`_rad_revcomp`, sequences)
}

sequence_to_bits <- function(sequences) {
    .Call(`_rad_sequence_to_bits`, sequences)
}

sequence_to_bitlist <- function(sequences) {
    .Call(`_rad_sequence_to_bitlist`, sequences)
}

bits_to_sequence <- function(input, sequence_length = 16L) {
    .Call(`_rad_bits_to_sequence`, input, sequence_length)
}

bits_to_hex <- function(input, sequence_length = 16L) {
    .Call(`_rad_bits_to_hex`, input, sequence_length)
}

revcomp_bits <- function(input, sequence_length = 16L) {
    .Call(`_rad_revcomp_bits`, input, sequence_length)
}

hamming_distance_rcpp <- function(a, b) {
    .Call(`_rad_hamming_distance_rcpp`, a, b)
}

generate_quaternary_mutations <- function(sequences, sequence_length = 32L) {
    .Call(`_rad_generate_quaternary_mutations`, sequences, sequence_length)
}

generate_recursive_quaternary_mutations <- function(sequences, mutation_rounds = 2L, sequence_length = 32L) {
    .Call(`_rad_generate_recursive_quaternary_mutations`, sequences, mutation_rounds, sequence_length)
}

shift_barcodes <- function(sequences, sequence_length, max_shift = 2L, verbose = FALSE) {
    .Call(`_rad_shift_barcodes`, sequences, sequence_length, max_shift, verbose)
}

barcode_correction_v3 <- function(true_barcodes, invalid_barcodes, true_counts, invalid_counts, mutation_rounds = 3L, sequence_length = 16L, nthread = 1L, max_shift = 3L, verbose = FALSE) {
    .Call(`_rad_barcode_correction_v3`, true_barcodes, invalid_barcodes, true_counts, invalid_counts, mutation_rounds, sequence_length, nthread, max_shift, verbose)
}

sigstream <- function(input_path, sigstringsFilePath, adapters, read_layout, misalignment_threshold, chunkSize, nthreads, outputPath, write_fastq = TRUE, compress = TRUE, max_sequences = -1L, min_length = 100L, verbose = FALSE) {
    invisible(.Call(`_rad_sigstream`, input_path, sigstringsFilePath, adapters, read_layout, misalignment_threshold, chunkSize, nthreads, outputPath, write_fastq, compress, max_sequences, min_length, verbose))
}

misalignment_stream <- function(input_path, adapters, nthreads = 1L, max_sequences = 500000L, chunk_size = 50000L) {
    .Call(`_rad_misalignment_stream`, input_path, adapters, nthreads, max_sequences, chunk_size)
}

tabulate_variable_sequences <- function(input_files, output_prefix, identity_elements, compress = TRUE, batch_size = 50000L) {
    invisible(.Call(`_rad_tabulate_variable_sequences`, input_files, output_prefix, identity_elements, compress, batch_size))
}

tabulate_sigs <- function(file_path, output_prefix, chunk_size = 50000L, max_sequences = -1L, nthreads = 1L, compress = TRUE, output_type = "summary") {
    invisible(.Call(`_rad_tabulate_sigs`, file_path, output_prefix, chunk_size, max_sequences, nthreads, compress, output_type))
}

extract_blaze_barcode <- function(fastq_file, print_every = 10000L) {
    .Call(`_rad_extract_blaze_barcode`, fastq_file, print_every)
}

extract_blaze_id_bc <- function(fastq_file, output_file, print_every = 10000L) {
    invisible(.Call(`_rad_extract_blaze_id_bc`, fastq_file, output_file, print_every))
}

fastq_correction <- function(input_file, output_file, incorrect_bcs, correct_bcs, barcode_id = "barcode", chunk_size = 50000L, print_freq = 10000L, nthreads = 4L, downsample = -1L) {
    .Call(`_rad_fastq_correction`, input_file, output_file, incorrect_bcs, correct_bcs, barcode_id, chunk_size, print_freq, nthreads, downsample)
}

