# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sigalign <- function(adapters, sequences, ids, misalignment_thresholds, nthreads) {
    .Call(`_rad_sigalign`, adapters, sequences, ids, misalignment_thresholds, nthreads)
}

sigalign_stats <- function(adapters, sequences, nthreads = 1L) {
    .Call(`_rad_sigalign_stats`, adapters, sequences, nthreads)
}

sig_run <- function(read_layout, misalignment_threshold, rcpp_sigstrings, verbose = FALSE) {
    .Call(`_rad_sig_run`, read_layout, misalignment_threshold, rcpp_sigstrings, verbose)
}

revcomp <- function(sequences) {
    .Call(`_rad_revcomp`, sequences)
}

sequence_to_bits <- function(sequences) {
    .Call(`_rad_sequence_to_bits`, sequences)
}

bits_to_sequence <- function(input, sequence_length) {
    .Call(`_rad_bits_to_sequence`, input, sequence_length)
}

revcomp_bits <- function(input, sequence_length) {
    .Call(`_rad_revcomp_bits`, input, sequence_length)
}

hamming_bits <- function(int64_a, int64_b, sequence_length) {
    .Call(`_rad_hamming_bits`, int64_a, int64_b, sequence_length)
}

generate_mutations <- function(sequences, sequence_length) {
    .Call(`_rad_generate_mutations`, sequences, sequence_length)
}

